[2025-06-09T04:06:53.349+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T04:06:53.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice manual__2025-06-09T04:06:51.518744+00:00 [queued]>
[2025-06-09T04:06:53.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice manual__2025-06-09T04:06:51.518744+00:00 [queued]>
[2025-06-09T04:06:53.382+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-09T04:06:53.395+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_netsuite_invoice> on 2025-06-09 04:06:51.518744+00:00
[2025-06-09T04:06:53.401+0000] {standard_task_runner.py:63} INFO - Started process 60 to run task
[2025-06-09T04:06:53.404+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NetSuite_Invoice_Daily_Extractor', 'fetch_netsuite_invoice', 'manual__2025-06-09T04:06:51.518744+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/crawl_netsuite.py', '--cfg-path', '/tmp/tmpbqjg1fuy']
[2025-06-09T04:06:53.407+0000] {standard_task_runner.py:91} INFO - Job 196: Subtask fetch_netsuite_invoice
[2025-06-09T04:06:53.455+0000] {task_command.py:426} INFO - Running <TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice manual__2025-06-09T04:06:51.518744+00:00 [running]> on host 6b5241449da9
[2025-06-09T04:06:53.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NetSuite_Invoice_Daily_Extractor' AIRFLOW_CTX_TASK_ID='fetch_netsuite_invoice' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T04:06:51.518744+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T04:06:51.518744+00:00'
[2025-06-09T04:06:53.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T04:06:54.369+0000] {logging_mixin.py:188} INFO - ‚úÖ ƒêƒÉng nh·∫≠p th√†nh c√¥ng.
[2025-06-09T04:06:54.698+0000] {logging_mixin.py:188} INFO - üìÑ N·ªôi dung response ƒë∆∞·ª£c ghi v√†o: /tmp/debug_invoice_raw.txt
[2025-06-09T04:06:54.699+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T04:06:54.699+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_netsuite.py", line 51, in fetch_invoice_data
    raise Exception("‚ùå NetSuite tr·∫£ v·ªÅ HTML thay v√¨ CSV. C√≥ th·ªÉ l·ªói quy·ªÅn, session timeout, ho·∫∑c c·∫ßn re-auth.")
Exception: ‚ùå NetSuite tr·∫£ v·ªÅ HTML thay v√¨ CSV. C√≥ th·ªÉ l·ªói quy·ªÅn, session timeout, ho·∫∑c c·∫ßn re-auth.
[2025-06-09T04:06:54.716+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=NetSuite_Invoice_Daily_Extractor, task_id=fetch_netsuite_invoice, run_id=manual__2025-06-09T04:06:51.518744+00:00, execution_date=20250609T040651, start_date=20250609T040653, end_date=20250609T040654
[2025-06-09T04:06:54.732+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 196 for task fetch_netsuite_invoice (‚ùå NetSuite tr·∫£ v·ªÅ HTML thay v√¨ CSV. C√≥ th·ªÉ l·ªói quy·ªÅn, session timeout, ho·∫∑c c·∫ßn re-auth.; 60)
[2025-06-09T04:06:54.782+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T04:06:54.813+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T04:06:54.815+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
