[2025-06-09T08:05:47.853+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T08:05:47.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 scheduled__2025-06-07T22:00:00+00:00 [queued]>
[2025-06-09T08:05:47.908+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 scheduled__2025-06-07T22:00:00+00:00 [queued]>
[2025-06-09T08:05:47.913+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-09T08:05:47.937+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Download_And_Upsert_F99> on 2025-06-07 22:00:00+00:00
[2025-06-09T08:05:47.947+0000] {standard_task_runner.py:63} INFO - Started process 33 to run task
[2025-06-09T08:05:47.952+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NetSuite_Daily_ToWarehouse_F99', 'Download_And_Upsert_F99', 'scheduled__2025-06-07T22:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/dag_netsuite.py', '--cfg-path', '/tmp/tmp1lr8didt']
[2025-06-09T08:05:47.955+0000] {standard_task_runner.py:91} INFO - Job 374: Subtask Download_And_Upsert_F99
[2025-06-09T08:05:48.024+0000] {task_command.py:426} INFO - Running <TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 scheduled__2025-06-07T22:00:00+00:00 [running]> on host cfb67c7eb5e0
[2025-06-09T08:05:48.436+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NetSuite_Daily_ToWarehouse_F99' AIRFLOW_CTX_TASK_ID='Download_And_Upsert_F99' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T22:00:00+00:00'
[2025-06-09T08:05:48.447+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T08:06:22.949+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T08:06:22.956+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_netsuite.py", line 36, in download_and_upsert_F99
    raise Exception("Không thể tải hoặc dữ liệu không hợp lệ")
Exception: Không thể tải hoặc dữ liệu không hợp lệ
[2025-06-09T08:06:22.995+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=NetSuite_Daily_ToWarehouse_F99, task_id=Download_And_Upsert_F99, run_id=scheduled__2025-06-07T22:00:00+00:00, execution_date=20250607T220000, start_date=20250609T080547, end_date=20250609T080622
[2025-06-09T08:06:23.027+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 374 for task Download_And_Upsert_F99 (Không thể tải hoặc dữ liệu không hợp lệ; 33)
[2025-06-09T08:06:23.050+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T08:06:23.083+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T08:06:23.086+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
