[2025-06-09T10:49:01.201+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T10:49:01.235+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NetSuite_22to24_Daily_ToWarehouse_F98.Upsert_F98_To_DataWarehouse scheduled__2025-06-07T22:00:00+00:00 [queued]>
[2025-06-09T10:49:01.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NetSuite_22to24_Daily_ToWarehouse_F98.Upsert_F98_To_DataWarehouse scheduled__2025-06-07T22:00:00+00:00 [queued]>
[2025-06-09T10:49:01.247+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-09T10:49:01.262+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Upsert_F98_To_DataWarehouse> on 2025-06-07 22:00:00+00:00
[2025-06-09T10:49:01.268+0000] {standard_task_runner.py:63} INFO - Started process 94 to run task
[2025-06-09T10:49:01.275+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NetSuite_22to24_Daily_ToWarehouse_F98', 'Upsert_F98_To_DataWarehouse', 'scheduled__2025-06-07T22:00:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/dag_netsuite_22to24.py', '--cfg-path', '/tmp/tmp9omomq9q']
[2025-06-09T10:49:01.280+0000] {standard_task_runner.py:91} INFO - Job 400: Subtask Upsert_F98_To_DataWarehouse
[2025-06-09T10:49:01.339+0000] {task_command.py:426} INFO - Running <TaskInstance: NetSuite_22to24_Daily_ToWarehouse_F98.Upsert_F98_To_DataWarehouse scheduled__2025-06-07T22:00:00+00:00 [running]> on host 87d36d91b2b5
[2025-06-09T10:49:01.427+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NetSuite_22to24_Daily_ToWarehouse_F98' AIRFLOW_CTX_TASK_ID='Upsert_F98_To_DataWarehouse' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T22:00:00+00:00'
[2025-06-09T10:49:01.428+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T10:49:01.506+0000] {warnings.py:110} WARNING - /opt/***/plugins/Project/TaraFunction.py:187: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-06-09T10:49:02.540+0000] {logging_mixin.py:188} INFO - [F99 → DW] Đã lấy 43149 dòng từ Datalake.
[2025-06-09T10:49:02.541+0000] {logging_mixin.py:188} INFO - [F99 → DW] Ghi chunk từ dòng 0 đến 43149
[2025-06-09T10:49:05.186+0000] {logging_mixin.py:188} INFO - [Datawarehouse] Ghi thành công 43149 dòng vào "NetSuite"."F98_CustomSearch_4532_22to24"
[2025-06-09T10:49:05.218+0000] {logging_mixin.py:188} INFO - [F99 → DW] Ghi thành công 43149 dòng vào Data Warehouse.
[2025-06-09T10:49:05.249+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-09T10:49:05.250+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T10:49:05.259+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NetSuite_22to24_Daily_ToWarehouse_F98, task_id=Upsert_F98_To_DataWarehouse, run_id=scheduled__2025-06-07T22:00:00+00:00, execution_date=20250607T220000, start_date=20250609T104901, end_date=20250609T104905
[2025-06-09T10:49:05.317+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-09T10:49:05.377+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T10:49:05.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
